#!/bin/bash
set -e

# Cd to repo root
cd "$(dirname "${BASH_SOURCE[0]}")/.."

./scripts/build

containerId=$(docker create ghcr.io/tankgameorg/ui:development)
rm -rf engine
docker cp $containerId:/app/engine/ .
