#!/bin/bash
set -e

# Cd to repo root
cd "$(dirname "${BASH_SOURCE[0]}")/.."

./scripts/build

containerId=$(docker create ryan3r/tank-game)

tmp=$(mktemp -d)
trap "rm -rf $tmp" EXIT

docker cp $containerId:/app/ $tmp
rm *.jar
cp $tmp/app/*.jar .
