#!/bin/bash
set -e

# Pin the included tank game engine to the last compatible version
ENGINE_VERSION=d91740c256611cedf7e097f8bc954c5912b045c0


checkout() {
    # Build tank game engine
    if [ -d "tankgame" ]; then
        git -C tankgame fetch origin
    else
        git clone https://github.com/TrevorBrunette/tankgame.git
    fi

    pushd tankgame &>/dev/null
    git checkout "${ENGINE_VERSION}"
    popd &>/dev/null
}

build() {
    pushd tankgame &>/dev/null
    mvn compile package

    # Rename the executable to include the git hash for easy debugging
    current_jar=$(echo target/TankGame-*.jar)
    mv $(echo "$current_jar") "target/$(basename "$current_jar" .jar)-$(git rev-parse --short HEAD)".jar

    popd &>/dev/null

    if [ -n "$1" ]; then
        mkdir -p "$1"
        mv -v tankgame/target/TankGame-*.jar "$1"
    fi
}

case "$1" in
    checkout)
        checkout
        ;;
    build)
        build "$2"
        ;;
    all)
        checkout
        build "$2"
        ;;
    *)
        echo "Usage: $0 <checkout|build|all> [copy-build-to]"
        ;;
esac
