#!/bin/bash

source "$(dirname "${BASH_SOURCE[0]}")/shared.sh"

case "$1" in
    frontend)
        cd frontend
        exec npx webpack serve
        ;;

    backend)
        cd backend
        exec node src/index.mjs cat ../tank_game_data.json
        ;;

    *)
        if [ -z "$TMUX" ]; then
            exec tmux new $0
        fi

        tmux split-pane $0 backend
        exec $0 frontend
        ;;
esac
